### PR TITLE
Website responsiveness

### LINKED ISSUE #6: Correct responsiveness of web site.
- There is a lot of space between sections in the mobile view.
- On certain laptop screens, the items overlap each other a little.

### LINKED ISSUE #9: Correct centering of `Follow Luke` section logos.
- The last section (`Follow Luke`) has 5 social media logos/icons and they are aligned to the left in the **desktop view**.
- Please make the logos/icons occupy the same space overall.

### PR DESCRIPTION
**Pull request by jydoskey**
1. Worked on the mobile reponsiveness of the website by removing some of the defined heights of the page which caused the skew in look on changed of device. 
2. Also helped fix the social icon lists
3. While doing the above I added a bootstrap file link to help with css styles and properties

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Hey @jydoskey, thank you SO much for making a PR!

There are some changes to be made
- Please correct the case of your surname in the `CONTRIBUTORS.md` file and make it Camel case.
- Please follow the correct commit message convention. (Refer to the `CONTRIBUTING.md` file.)
- This is a vanilla CSS (with Flexbox) project and I don't want any CSS framework as a part of the code base. So please remove Bootstrap from the project and use vanilla CSS for changes. I am really sorry for the inconvenience, as I now realize that I should've mentioned that in the `CONTRIBUTING.md` file. I will add it once you make a PR.
- Also, I don't want any inline CSS. All the styling should be in the `style.css` file.
- You have made changes to the heading font size and I prefer the way it looked before, so please revert those changes.
- There is an indentation error from line no. 62 onwards in `index.html`. Please correct that.
- For the links, please change the hover colour as the current blue color cannot be seen on the black background.
- Throughout the file, you have made the `height: auto;`, which is the default value of height, so you should remove those redundant statements. (There is a specific section where I want you to keep it. I've mentioned it below.)
- Now let us go section-wise
   - Landing page: I prefer the previous `header` alignment and sub-text (below 'Laidback Luke' in the `main` section) font size. (Let `body` have a `margin: auto;` property.)
   - `Real DJing` section
      - The width should be 90% (with an auto margin) (the picture is touching the borders of the screen in both, the desktop and the mobile view. Please correct that.
      - I want you to keep the height at 100vh for this section (and handle it in the responsiveness section for other screens by maybe adding the `height: auto` property deliberately.) as the user should have to see only one section at a time. (Right now I can see the header of the next section on the same page as the `Real DJing` section and it is very distracting for the user.)
   - `Social Media` section: Please correct the Laidback Luke logo if you can. (It appears stretched in the Mobile view.)

**Comment by HarshKapadia2** [comment]
Issues #6 and #9 attempted to be solved via this PR.

**Comment by HarshKapadia2** [comment]
Hey are you going to be making the changes, @jydoskey? I am so sorry for so many changes!
You can make a completely new PR as well, your choice.
Let me know whatever you want to do.
It's okay if you aren't able to make another PR as well, but do let me know!

**Comment by jydoskey** [comment]
I will get to them, that's fine. Will let you know once done. Thanks

**Comment by HarshKapadia2** [comment]
Okay!

**Comment by HarshKapadia2** [comment]
Any updates, @jydoskey ?

**Comment by jydoskey** [comment]
This night, will get the updates across

**Comment by HarshKapadia2** [comment]
Alright, take your time! Just wanted to know whether you were planning to do it or not. 👍

**Comment by jydoskey** [comment]
1. So I updated the PR, the issue with the font size being changed is as a result of the content view height changing.
2. And setting the height to auto which I had done was to cater for the mobile view. On setting the viewheight to 100 which you had asked, all the contents contained in that section don't seem to fit right into that space. So the skewness which I had removed earlier has been re-introduced.
Asides the listed above, all others have been handled.

**Comment by HarshKapadia2** [comment]
Thank you for making the necessary changes, @jydoskey!

For your reference (check the mobile view and the desktop view both):
The original site: https://harshkapadia2.github.io/lbl-tribute-page/
The site with your PR: https://harshkapadia2.github.io/lbl-test/

There are some issues in your PR that need to be fixed.
- Please center the header.
- Please keep the original heading font size.
- The `vlog` section is overlapping the `DJ` section in mobile view.
- The `vlog` section should have a 80% width (margin: auto).
- The `productivity` section is overlapping the `vlog` section in mobile view.
- Add `height: auto;` for the `follow` section in the class `follow-section` in `style.css`.

**Comment by jydoskey** [comment]
Okay, will go through both and work on them.

**Comment by jydoskey** [comment]
@HarshKapadia2 you can go over them again

**Comment by HarshKapadia2** [comment]
Well done, @jydoskey! 🎉 ✨
The last commit solves everything! I will be merging your PR.
Thank you SO much for contributing to this project and I apologize for making you change things again and again!
I hope you consider contributing more! 😃

**Comment by HarshKapadia2** [comment]
Issues #6 and #9 solved via this PR (#11).

**Comment by jydoskey** [comment]
Thanks @HarshKapadia2 , it was actually fun working with you. No issues with changing things always as much as the end goal was achieved. I sure will consider that.

**Pull request merged**
